// Get images
// https://www.flickr.com/photos/195241587@N06/with/51944722029/

const ProjectsGallery = [
    {
        id: 1,
        imageSrc: "https://live.staticflickr.com/65535/52191411398_028eb10e3f_b.jpg",
        caption: "About Me",
        desc: "This is a mini project based on html5. Just to start!",
        githubLink: "https://github.com/abduldaim-ad/html_web_page",
    },
    {
        id: 2,
        imageSrc: "https://live.staticflickr.com/65535/52191393316_29df75d4af_b.jpg",
        caption: "Resume",
        desc: "This is also a mini project based on html5 for practice of advanced html5 elements.",
        githubLink: "https://github.com/abduldaim-ad/HTML",
    },
    {
        id: 3,
        imageSrc: "https://live.staticflickr.com/65535/52190379932_a37d7681d2_b.jpg",
        caption: "Website Layout",
        desc: "This project is based on understanding the layout of websites.",
        githubLink: "https://github.com/abduldaim-ad/html-css_practice_website",
    },
    {
        id: 4,
        imageSrc: "https://live.staticflickr.com/65535/52190381077_716e568a53_b.jpg",
        caption: "Search Bar Frontend",
        desc: "Just a frontend with a search bar and a table with dummy data.",
        githubLink: "https://github.com/abduldaim-ad/Search_Bar_Filter_Table",
    },
    {
        id: 5,
        imageSrc: "https://live.staticflickr.com/65535/52190381757_d7a4feba79_b.jpg",
        caption: "Navbar JSX Practice",
        desc: "To design a simple navbar to practice JS XML.",
        githubLink: "https://github.com/abduldaim-ad/ReactJS_Practice",
    },
    {
        id: 6,
        imageSrc: "https://live.staticflickr.com/65535/52190382102_a82da4c4af_b.jpg",
        caption: "E-Bell C2C Webpage",
        desc: "Simple design of E-commerce web page with a navbar and gradient look.",
        githubLink: "https://github.com/abduldaim-ad/E-Bell_C2C_Website_Practice",
    },
    {
        id: 7,
        imageSrc: "https://live.staticflickr.com/65535/52191391726_e92632f2b2_b.jpg",
        caption: "Ultimate Frisbee Website",
        desc: "This project is for the practice of CSS. A website with some styled text/table/image.",
        githubLink: "https://github.com/abduldaim-ad/html_css_practice",
    },
    {
        id: 8,
        imageSrc: "https://live.staticflickr.com/65535/52191392371_5374d7405e_b.jpg",
        caption: "Portfolio HTML/CSS",
        desc: "Simple one page portfolio to practice html/css.",
        githubLink: "https://github.com/abduldaim-ad/Porfolio-Website",
    },
    {
        id: 9,
        imageSrc: "https://live.staticflickr.com/65535/52190381887_39f0b26708_b.jpg",
        caption: "Website Boostrap Practice",
        desc: "This simple website was developed to practice the basics of bootstrap.",
        githubLink: "https://github.com/abduldaim-ad/quiz_app_practice",
    },
    {
        id: 10,
        imageSrc: "https://live.staticflickr.com/65535/52190382207_4f11b80ccb_b.jpg",
        caption: "Quiz App",
        desc: "Simple quiz app which has four questions with a submit button.",
        githubLink: "https://github.com/abduldaim-ad/QuizJS",
    },
    {
        id: 11,
        imageSrc: "https://live.staticflickr.com/65535/52191411003_04a1535707_b.jpg",
        caption: "Portfolio Bootstrap",
        desc: "This portfolio is deployed and developed using html/css/bootstrap.",
        githubLink: "https://github.com/abduldaim-ad/portfolio-ad",
    },
    {
        id: 12,
        imageSrc: "https://live.staticflickr.com/65535/52191651784_5e854d25d5_b.jpg",
        caption: "Form Auto Complete JS",
        desc: "On clicking the checkbox, the data of previous fields is copied to the next fields.",
        githubLink: "https://github.com/abduldaim-ad/form",
    },
    {
        id: 13,
        imageSrc: "https://live.staticflickr.com/65535/52191394596_7a227b5538_b.jpg",
        caption: "Hover to Display JS",
        desc: "On hovering over small image, that particular image is displayed in large div.",
        githubLink: "https://github.com/abduldaim-ad/gallery",
    },
    {
        id: 14,
        imageSrc: "https://live.staticflickr.com/65535/52191408768_af8cb280db_b.jpg",
        caption: "Simple Calculator",
        desc: "This is very simple calculator to practice the basics of React.js.",
        githubLink: "https://github.com/abduldaim-ad/simple_calculator_react",
    },
    {
        id: 15,
        imageSrc: "https://live.staticflickr.com/65535/52191391856_836a3b2ff5_b.jpg",
        caption: "Top Three",
        desc: "This website displays the top three programming languages (dummy data).",
        githubLink: "https://github.com/abduldaim-ad/top_three_react_app",
    },
    {
        id: 16,
        imageSrc: "https://live.staticflickr.com/65535/52190383507_bfa6fc907b_b.jpg",
        caption: "Greeting Website",
        desc: "Good Morning, Good Afternoon and Good Night based on current time.",
        githubLink: "https://github.com/abduldaim-ad/greeting_website_reactjs",
    },
    {
        id: 17,
        imageSrc: "https://live.staticflickr.com/65535/52191392921_3f0dbcb8a5_b.jpg",
        caption: "Navbar React Router",
        desc: "This mini-project is to practice how React.js uses the concept of virtual-DOM.",
        githubLink: "https://github.com/abduldaim-ad/navbar",
    },
    {
        id: 18,
        imageSrc: "https://live.staticflickr.com/65535/52191648789_462d8caaef_b.jpg",
        caption: "ToDo List React.js",
        desc: "We can add to or remove items from the list. The items are inserted in a sorted manner.",
        githubLink: "https://github.com/abduldaim-ad/todo_list_reactjs",
    },
    {
        id: 19,
        imageSrc: "https://live.staticflickr.com/65535/52191879805_4b17921792_b.jpg",
        caption: "Instagram Clone Practice (MERN)",
        desc: "This was my first project using complete MERN for the practice of MERN Stack. Getting started with Reactjs!",
        githubLink: "https://github.com/abduldaim-ad/Instagram_Clone_Practice",
    },
    {
        id: 20,
        imageSrc: "https://live.staticflickr.com/65535/52191409058_02b819560a_b.jpg",
        caption: "This Current Portfolio",
        desc: "This portfolio is being developed in React.js. You can check the source code using below GitHub Link.",
        githubLink: "https://github.com/abduldaim-ad/portfolio",
    },
    {
        id: 21,
        imageSrc: "https://live.staticflickr.com/65535/52191394721_c271835001_b.jpg",
        caption: "E-Seller (MERN)",
        desc: "E-Seller was my semester project of web engineering. It has Sign In/Sign Up, Cart, Checkout, Pending Orders, etc.",
        githubLink: "https://github.com/abduldaim-ad/semester_project",
    },
    {
        id: 22,
        imageSrc: "https://live.staticflickr.com/65535/52229492990_a4e1a30974_b.jpg",
        caption: "Landing Page",
        desc: "Based on the concepts of props and components reusability. This was good to practice the concepts of React.js.",
        githubLink: "https://github.com/abduldaim-ad/react-practice",
    },
    {
        id: 23,
        imageSrc: "https://live.staticflickr.com/65535/52227968247_e08dca683a_b.jpg",
        caption: "AU Website 1",
        desc: "This project is made in HTML and CSS and has three web pages. It also has a google map displayed in the Contact Us page.",
        githubLink: "https://github.com/abduldaim-ad/au_website_html_css_lab_two",
    },
    {
        id: 24,
        imageSrc: "https://live.staticflickr.com/65535/52229543530_254067da44_b.jpg",
        caption: "AU Website 2",
        desc: "This website has a background video placed at the header. It has also a beautiful table with hover effect.",
        githubLink: "https://github.com/abduldaim-ad/au_website_html_css",
    },
    {
        id: 25,
        imageSrc: "https://live.staticflickr.com/65535/52228022532_fd910df6b5_b.jpg",
        caption: "Create User",
        desc: "Developed in HTML/CSS/JS and has functionality to add the information of user to the table.",
        githubLink: "https://github.com/abduldaim-ad/create-user",
    },

];

export default ProjectsGallery.reverse();